In [9]:
import numpy as np
import pandas as pd

cities = ['Berlin', 'Frankfurt', 'Hamburg',
'Nuremberg', 'Munich', 'Stuttgart',
'Hanover', 'Saarbruecken', 'Cologne',
'Constance', 'Freiburg', 'Karlsruhe'
]
n= len(cities)
n= len(cities)
data = {'Temperature': np.random.normal(30, 10, n),
'Humidity': np.random.normal(78, 10, n),
'Wind': np.random.normal(15, 10, n)
}
df = pd.DataFrame(data=data, index=cities)
df

              Temperature   Humidity       Wind
Berlin          25.463931  74.743673   7.952866
Frankfurt       41.423199  89.507623  10.743496
Hamburg         38.511538  72.413901   0.823476
Nuremberg       32.162052  57.445694  17.901035
Munich          21.442832  75.385362  28.228686
Stuttgart       18.132913  73.151957  21.119130
Hanover         17.365354  59.949665  14.723557
Saarbruecken    32.741705  83.826916   4.797003
Cologne         31.472339  90.220255   6.317790
Constance       32.090263  87.177458  17.891725
Freiburg         9.110993  86.729241  20.512409
Karlsruhe       40.340779  85.335422  25.412597